spellchecker: aspell

matrix:
- name: Markdown
  sources:
  - '*.md'
  - 'docs/**/*.md'
  aspell:
    lang: en
    d: en_GB
    ignore-case: true
  hunspell:
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    output: .wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: ':'
        content: '[\w-]*'
        close: ':'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.snippets
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - blockquote
      - span
      - a
      - :matches(.csl-bib-body)
  - pyspelling.filters.url:

