# Project information
site_name: SPM Documentation
site_url: https://www.fil.ion.ucl.ac.uk/spm/docs/
site_author: SPM Team
site_description: >-
  Documentation of the SPM Software for neuroimaging

# Repository
repo_url: https://github.com/spm/spm
repo_name: spm/spm
edit_uri: https://github.com/spm/spm-docs/blob/main/docs/

# Copyright
copyright: Copyright &copy; 1991 - 2023 SPM Team and Collaborators

# Configuration
theme:
  name: material
  palette:
   - media: "(prefers-color-scheme)"
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-auto
       name: Switch to light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-7
       name: Switch to dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: blue grey
     accent: deep orange
     toggle:
       icon: material/brightness-4
       name: Switch to system preference
  logo: assets/images/spm_logo_white.png
  favicon: assets/images/spm_favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - 'Home':
    - 'index.md'
    - 'Installation': 'installation/index.md'
    - 'Tutorials':    'tutorials/index.md'
    - 'Development':  'development/index.md'
  - 'Getting started':
    - 'installation/index.md'
    - 'Installation': 'installation/index.md'
    - 'Standalone':   'installation/standalone.md'
    - 'Containers':   'installation/containers.md'
    - 'Octave':       'installation/octave.md'
  - 'Courses':
    - 'courses/index.md'
    - 'M/EEG':
      - 'courses/eeg_meg/index.md'
    - 'fMRI/VBM': 
      - 'courses/fmri_vbm/index.md'
      - 'Lecture recordings':
        - 'Spatial preprocessing':            'courses/fmri_vbm/recordings/preprocessing.md'
        - 'General linear model':             'courses/fmri_vbm/recordings/glm.md'
        - 'Contrasts & classical inference':  'courses/fmri_vbm/recordings/contrasts_classical_inference.md'
        - 'Group analysis':                   'courses/fmri_vbm/recordings/group_analysis.md'
        - 'Random field theory':              'courses/fmri_vbm/recordings/random_field_theory.md'
        - 'Voxel-based morphometry':          'courses/fmri_vbm/recordings/vbm.md'
        - 'Experimental design':              'courses/fmri_vbm/recordings/experimental_design.md'
        - 'Event-related fMRI':               'courses/fmri_vbm/recordings/event_related_fmri.md'
        - 'Bayesian inference':               'courses/fmri_vbm/recordings/bayesian_inference.md'
        - 'Introduction to DCM':              'courses/fmri_vbm/recordings/dcm_introduction.md'
        - 'DCM: Testing hypotheses':          'courses/fmri_vbm/recordings/dcm_hypothesis_testing.md'
  - 'Tutorials':
    - 'tutorials/index.md'
    - 'fMRI':
      - 'tutorials/fmri/index.md'
      - 'Block Design fMRI':
        - 'Getting started':         'tutorials/fmri/block/index.md'
        - 'Preprocessing':
          - 'Introduction':            'tutorials/fmri/block/preprocessing/introduction.md'
          - 'Visual inspection':       'tutorials/fmri/block/preprocessing/visual_inspection.md'
          - 'Removal of dummy scans':  'tutorials/fmri/block/preprocessing/dummy_scans.md'
          - 'Realignment':             'tutorials/fmri/block/preprocessing/realignment.md'
          - 'Slice timing correction': 'tutorials/fmri/block/preprocessing/slice_timing.md'
          - 'Coregistration':          'tutorials/fmri/block/preprocessing/coregistration.md'
          - 'Segmentation':            'tutorials/fmri/block/preprocessing/segmentation.md'
          - 'Normalisation':           'tutorials/fmri/block/preprocessing/normalisation.md'
          - 'Smoothing':               'tutorials/fmri/block/preprocessing/smoothing.md'
          - 'Batch interface':         'tutorials/fmri/block/preprocessing/batch.md'
          - 'Scripting':               'tutorials/fmri/block/preprocessing/scripting.md'
        - 'Statistical modelling':
          - 'First-level modelling - block design': 'tutorials/fmri/block/modelling/block_design.md'
      - 'Event-related fMRI':
        - 'Getting started':       'tutorials/fmri/event/index.md'
        - 'Preprocessing':         'tutorials/fmri/event/preprocessing.md'
        - 'Categorical Modelling': 'tutorials/fmri/event/categorical.md'
        - 'Parametric Modelling':  'tutorials/fmri/event/parametric.md'
        - 'Bayesian Analysis':     'tutorials/fmri/event/bayesian.md'
    - 'VBM':
        - 'Getting started':      'tutorials/vbm/index.md'
        - 'Image processing':     'tutorials/vbm/image_processing.md'
        - 'Statistical analysis': 'tutorials/vbm/statistical_analysis.md'
    - 'M/EEG':
      - 'Getting Started':              'tutorials/MEEG/index.md'
      - 'EEG Mismatch negativity data': 'tutorials/MEEG/mmn/index.md'
      - 'M/EEG Convolution modelling':  'tutorials/MEEG/meeg_firstlevel.md'
      - 'MEG Source localisation':      'tutorials/MEEG/meg_sloc.md'
      - 'Multimodal':
        - 'Introduction': 'tutorials/MEEG/multimodal/index.md'
        - 'EEG':          'tutorials/MEEG/multimodal/eeg.md'
        - 'MEG':          'tutorials/MEEG/multimodal/meg.md'
        - 'fMRI':         'tutorials/MEEG/multimodal/fmri.md'
        - 'Fusion':       'tutorials/MEEG/multimodal/fusion.md'
      - 'Multimodal, multisubject data fusion':
        - 'Overview':                'tutorials/MEEG/multi/index.md'
        - 'Preprocessing':           'tutorials/MEEG/multi/preprocessing.md'
        - 'Evoked analysis':         'tutorials/MEEG/multi/evoked.md'
        - 'Time-frequency analysis': 'tutorials/MEEG/multi/timefrequency.md'
        - 'fMRI':                    'tutorials/MEEG/multi/fmri.md'
        - 'Source':                  'tutorials/MEEG/multi/source.md'
        - 'References':              'tutorials/MEEG/multi/references.md'
    - 'OPM':
        - 'Getting Started':               'tutorials/opm/index.md'
        - 'Sensor Level: Evoked Response': 'tutorials/opm/evoked/index.md'
        - 'Source Level: Evoked Response': 'tutorials/opm/evoked_source/index.md'
        - 'Coregistration':                'tutorials/opm/coreg/index.md'
        - 'Simulation':                    'tutorials/opm/simulation/index.md'
    - 'DCM':
        - 'Overview of DCM':                  'tutorials/dcm/index.md'
        - 'DCM for fMRI - 1st level (Attention)': 'tutorials/dcm/dcm_fmri_first_level_gui.md'       
        - 'DCM for fMRI - 1st level (Language)':  'tutorials/dcm/dcm_fmri_first_level.md'
        - 'DCM for fMRI - 2nd level (Language)':  'tutorials/dcm/dcm_fmri_second_level.md'
        - 'DCM for Evoked Responses':         'tutorials/dcm/dcm_erp.md'
        - 'DCM for Induced Responses':        'tutorials/dcm/dcm_ir.md'
        - 'DCM for Phase Coupling':           'tutorials/dcm/dcm_phase.md'
        - 'DCM for Steady State Responses':   'tutorials/dcm/dcm_ssr.md'
        - 'DCM for Cross-Spectral Densities': 'tutorials/dcm/dcm_csd.md'
    - 'DAiSS':
      - 'Overview of DAiSS': 'tutorials/daiss/index.md'
      - 'Beamforming':       'tutorials/daiss/daiss_beamforming.md'
  #- 'Reference': 'reference/index.md'
  - 'Development':
    - 'Introduction': 'development/index.md'
    - 'Git':          'development/git.md'
    - 'Guidelines':   'development/guidelines.md'
    - 'Testing':      'development/testing.md'
    - 'Compilation':  'development/compilation/index.md'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  #- mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - toc:
      permalink: true

plugins:
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "42.172vw"
      is_video: True
      video_autoplay: False
  - bibtex:
      bib_file: "docs/assets/bib/spm.bib"
  - search:
      lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spm
    - icon: fontawesome/solid/brain
      link: https://www.fil.ion.ucl.ac.uk/spm/

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
