site_name: SPM Documentation

theme:
  name: material
  palette:
    primary: blue grey
    accent: deep orange 
  logo: assets/images/spm_logo_white.png
  favicon: assets/images/spm_favicon.png
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - 'Tutorials':
    - 'fMRI':
      - 'Preprocessing':
        - 'Introduction to preprocessing': './tutorials/fmri_preprocessing/introduction.md'
        - 'Visual inspection of the data': './tutorials/fmri_preprocessing/visual_inspection.md'
        - 'Removal of dummy scans': './tutorials/fmri_preprocessing/dummy_scans.md'
        - 'Realignment': './tutorials/fmri_preprocessing/realignment.md'
        - 'Slice timing correction': './tutorials/fmri_preprocessing/slice_timing.md'
        - 'Coregistration': './tutorials/fmri_preprocessing/coregistration.md'
        - 'Segmentation': './tutorials/fmri_preprocessing/segmentation.md'
        - 'Normalisation': './tutorials/fmri_preprocessing/normalisation.md'
        - 'Smoothing': './tutorials/fmri_preprocessing/smoothing.md'
        - 'Batch interface': './tutorials/fmri_preprocessing/batch.md'
      - 'Statistical modelling':
        - 'First-level modelling - block design': './tutorials/fmri_modelling/block_design.md'
        - 'First-level modelling - event-related design': './tutorials/fmri_modelling/event_related_design.md'
        - 'Group-level modelling': './tutorials/fmri_modelling/group_level.md'
  - Courses: 'https://www.fil.ion.ucl.ac.uk/spm/course/'
  - Support: 'https://www.fil.ion.ucl.ac.uk/spm/support/'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "42.172vw"
      is_video: True
      video_autoplay: False 
  - search:
      lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/solid/brain
      link: https://www.fil.ion.ucl.ac.uk/spm/

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
