site_name: SPM Documentation
repo_url: https://github.com/spm/spm
theme:
  name: material
  features:
    - header.autohide
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
plugins:
  - search:
      lang: en
extra:
  generator: false
  social:
    - icon: fontawesome/solid/brain
      link: https://www.fil.ion.ucl.ac.uk/spm/
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js