name: Links Check
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
  workflow_dispatch:
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.markdown-link-check.json'
          folder-path: 'docs/tutorials'
          file-path: './README.md, ./docs/index.md, ./docs/installation.md'
          base-branch: main
